services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mynet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  face-api:
    image: face-api:latest
    build:
      context: ./face-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./face-api:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - mynet
    restart: unless-stopped

  my-backend:
    build:
      context: ./my-backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    env_file:
      - ./my-backend/.env.production
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
      face-api:
        condition: service_started
    networks:
      - mynet
    restart: unless-stopped

  my-frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./my-frontend/.env.production
    networks:
      - mynet
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public/images:/usr/share/nginx/html/images:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - my-backend
      - my-frontend
    networks:
      - mynet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mssql_data:
  backend_logs:
  backend_uploads:
  nginx_logs:

networks:
  mynet:
    driver: bridge
