services:
  backend:
    build: ./my-backend
    ports:
      - "5000:5000"
    volumes:
      - ./my-backend:/app
      - /app/node_modules  # Tránh lỗi node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]  # Dùng Nodemon thay vì Node.js thuần
    depends_on:
      - sqlserver


  frontend:
    build: ./my-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./my-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]  # Chạy Vite
    depends_on:
      - backend


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: egapet-sqlserver
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d  # Gắn thư mục chứa SQL scripts
    entrypoint: ["/bin/bash", "-c", " /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '123' -i /docker-entrypoint-initdb.d/EgaPets_Nhom_Quyen.sql && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '123' -i /docker-entrypoint-initdb.d/EgaPets_Scripts_ALL.sql && tail -f /dev/null"]
